### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Ri0n** [psi-im/psimedia#5]
```c++
(gdb) bt
#0  PsiMedia::RtpChannel::write (this=0x0, rtp=...) at psimedia/psimedia.cpp:859
No locals.
#1  0x00005555556deef1 in AvTransmit::transport_readyRead (this=<optimized out>) at avcall/avcall.cpp:257
        jpacket = {type = JingleRtp::Audio, portOffset = 0, value = {d = 0x7fff78007af0}}
#2  AvTransmit::qt_static_metacall (_o=0x55555713fa10, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at .moc/avcall.moc:82
        _t = 0x55555713fa10
#3  0x00007ffff5a921c9 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
No symbol table info available.
#4  0x0000555555b2e257 in JingleRtpChannel::readyRead (this=<optimized out>) at .moc/moc_jinglertp.cpp:295
No locals.
#5  0x00005555556d61d0 in JingleRtpChannelPrivate::ice_readyRead (this=0x55555a874570, componentIndex=0) at avcall/jinglertp.cpp:1654
        ice = <optimized out>
#6  0x00005555556d625c in JingleRtpChannelPrivate::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at .moc/jinglertp.moc:319
        _t = <optimized out>
#7  0x00007ffff5a921c9 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
No symbol table info available.
#8  0x0000555555c81e28 in XMPP::Ice176::readyRead (this=<optimized out>, _t1=<optimized out>, _t1@entry=0) at moc_ice176.cpp:236
        _a = {0x0, 0x7fff86ffc32c}
#9  0x0000555555c7df1a in XMPP::Ice176::Private::it_readyRead (this=0x555558868f60, path=0) at ice176.cpp:1074
        at = <optimized out>
        componentIndex = 0
        reskey = {d = 0x7fff78007ce0}
        msg = {d = {d = 0x0}}
        buf = {d = 0x7fff78007af0}
        requser = {static null = {<No data fields>}, d = 0x7fff78004100}
        msg = {d = {d = 0x0}}
        fromAddr = {d = {d = 0x7fff78007870}}
        fromPort = 8020
        reqkey = {d = 0x7fff78007c50}
        result = XMPP::StunMessage::ErrorFormat
        it = 0x555558d2f430
        cc = @0x55555769c8f0: {id = 6, info = {addr = {addr = {d = {d = 0x55555769c970}}, port = 41537}, type = XMPP::IceComponent::ServerReflexiveType, 
            priority = 1694498559, foundation = {static null = {<No data fields>}, d = 0x55555784f1f0}, componentId = 1, base = {addr = {d = {
                  d = 0x55555769c9a0}}, port = 41537}, related = {addr = {d = {d = 0x55555b8da1a0}}, port = -1}, id = {static null = {<No data fields>}, 
              d = 0x55555769c8a0}, network = -1}, iceTransport = 0x555558d2f430, path = 0}
        sock = 0x555558d2f430
#10 0x0000555555c75130 in XMPP::Ice176::Private::qt_static_metacall (_o=0x555558868f60, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at ice176.moc:122
        _t = 0x555558868f60
#11 0x00007ffff5a921c9 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
No symbol table info available.
#12 0x0000555555cb0a68 in XMPP::IceTransport::readyRead (this=<optimized out>, _t1=<optimized out>, _t1@entry=0) at moc_icetransport.cpp:209
        _a = {0x0, 0x7fff86ffc5ac}
#13 0x0000555555cadf1f in XMPP::IceLocalTransport::Private::sock_readyRead (this=0x5555578b4d50) at icelocaltransport.cpp:519
        watch = {d = 0x7fff78003400}
        dreads = {<QListSpecialMethods<XMPP::IceLocalTransport::Private::Datagram>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {
                    _q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, 
                array = {0x0}}, d = 0x7fff780078a0}, d = 0x7fff780078a0}}
        rreads = {<QListSpecialMethods<XMPP::IceLocalTransport::Private::Datagram>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {
                    _q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0,{0x0}}, d = 0x7ffff5b093e0 <QListData::shared_null>}, d = 0x7ffff5b093e0 <QListData::shared_null>}}
#14 0x0000555555caaf12 in XMPP::IceLocalTransport::Private::qt_static_metacall (_o=0x5555578b4d50, _c=<optimized out>, _id=<optimized out>, 
    _a=<optimized out>) at icelocaltransport.moc:284
        _t = 0x5555578b4d50
#15 0x00007ffff5a921c9 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
No symbol table info available.
#16 0x0000555555ca975f in XMPP::SafeUdpSocket::readyRead (this=<optimized out>) at icelocaltransport.moc:154
No locals.
#17 0x0000555555ca980d in XMPP::SafeUdpSocket::sock_readyRead (this=<optimized out>) at icelocaltransport.cpp:126
No locals.
#18 XMPP::SafeUdpSocket::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at icelocaltransport.moc:90
        _t = <optimized out>
#19 0x00007ffff5a921c9 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
No symbol table info available.
#20 0x00007ffff604fe95 in ?? () from /usr/lib64/libQt5Network.so.5
No symbol table info available.
#21 0x00007ffff604ff4c in ?? () from /usr/lib64/libQt5Network.so.5
No symbol table info available.
#22 0x00007ffff605ac81 in ?? () from /usr/lib64/libQt5Network.so.5
No symbol table info available.
#23 0x00007ffff68cbb3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
No symbol table info available.
#24 0x00007ffff68d32b9 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
No symbol table info available.
#25 0x000055555589e901 in PsiApplication::notify (this=0x7fffffffd490, receiver=0x55555adda790, event=0x7fff86ffcc70) at psiapplication.cpp:179
No locals.
#26 0x00007ffff5a6b0ca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
No symbol table info available.
#27 0x00007ffff5ab95ef in ?? () from /usr/lib64/libQt5Core.so.5
No symbol table info available.
#28 0x00007fffefc115a7 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#29 0x00007fffefc11810 in ?? () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#30 0x00007fffefc118bc in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#31 0x00007ffff5ab8cbf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
No symbol table info available.
#32 0x00007ffff5a6a04a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
No symbol table info available.
#33 0x00007ffff6e866e5 in QCA::SyncThread::run() () from /usr/lib64/libqca-qt5.so.2
No symbol table info available.
#34 0x00007ffff58d384c in ?? () from /usr/lib64/libQt5Core.so.5
No symbol table info available.
#35 0x00007ffff5614897 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#36 0x00007ffff4245cff in clone () from /lib64/libc.so.6
No symbol table info available.
```

**Comment by Ri0n** [comment]
the remote (crashed) side didn't have audio src/sink. maybe it could affect.

**Comment by Ri0n** [comment]
fixed

**Comment by Vitozz** [comment]
Demo crashed on Manjaro Linux
https://pastebin.com/FJqp8arZ
